version: '3.4'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: smart_devices
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
